services:
  mariadb:
    image: mariadb:10.6.19
    container_name: mariadb_local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: rntPy1
      MYSQL_USER: g8
      MYSQL_PASSWORD: hk49-Sk94K23m
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    container_name: adminer_local
    restart: unless-stopped
    ports:
      - "9402:8080"
    depends_on:
      - mariadb
